python3 add_values_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o add_values_logs
python3 average_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o average_logs
python3 cnt_non_zeros_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o cnt_non_zeros_logs
python3 cnt_zeros_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o cnt_zeros_logs
python3 durbinWatson_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o durbinWatson_logs
python3 entropy_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o entropy_logs
python3 find_magnitude_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o find_magnitude_logs
python3 find_max_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o find_max_logs
python3 find_max2_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o find_max2_logs
python3 find_median_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o find_median_logs
python3 find_min_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o find_min_logs
python3 geometric_mean_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o geometric_mean_logs
python3 harmonicMean_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o harmonicMean_logs
python3 kurtosis_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o kurtosis_logs
python3 max_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o max_logs
python3 min_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o min_logs
python3 product_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o product_logs
python3 safeNorm_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o safeNorm_logs
python3 sampleVariance_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o sampleVariance_logs
python3 skew_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o skew_logs
python3 sum_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o sum_logs
python3 sumOfLogarithms_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o sumOfLogarithms_logs
python3 variance_executer.py -i '/Users/alduck/Documents/GitHub/AST2024-SelectingConstrainingMRsScSoft/Step_1_TD-Generation/inputs/test_data_L-50_H50_int.json' -o variance_logs